// 高寨村家族族谱 - 模拟数据
// 说明：以父系血缘（fatherId）为主线组织族谱，配偶通过 spouseId 关联。
// 每个人节点包含：辈分（由 fatherId 链自动推导，无需手填）、生日、是否已故、
// 照片、简介、隐私字段（手机号，仅认证本人/直系可见）。

// 关系类型：
// - fatherId: 父亲节点 id（族谱主线）
// - spouseId: 配偶节点 id
// - isMarriedIn: 是否为"嫁入/娶入"的外姓配偶（布局时依附于伴侣，不单独占血缘树）
// - relationType: 'birth'(亲生) | 'adopted'(过继/收养) 预留字段

export const CURRENT_USER_ID = 'p_gaowei'; // 当前登录认证用户：高伟

export const initialPersons = [
  // ===== 第 0 代：曾祖辈 =====
  {
    id: 'p_taiye',
    name: '高守业',
    gender: 'male',
    birthDate: '1920-03-12',
    deceased: true,
    deceasedDate: '1998-11-02',
    fatherId: null,
    spouseId: 'p_taiye_w',
    photo: '',
    bio: '高寨村高氏一族始迁祖，早年务农，育有二子，为人正直，村中德高望重。',
    phone: '',
    relationType: 'birth',
  },
  {
    id: 'p_taiye_w',
    name: '陈氏',
    gender: 'female',
    birthDate: '1923-07-20',
    deceased: true,
    deceasedDate: '2001-05-18',
    fatherId: null,
    spouseId: 'p_taiye',
    isMarriedIn: true,
    photo: '',
    bio: '高守业之妻，勤俭持家。',
    phone: '',
    relationType: 'birth',
  },

  // ===== 第 1 代：祖辈 =====
  {
    id: 'p_changhai',
    name: '高长海',
    gender: 'male',
    birthDate: '1948-01-15',
    deceased: true,
    deceasedDate: '2020-08-09',
    fatherId: 'p_taiye',
    spouseId: 'p_changhai_w',
    photo: '',
    bio: '高守业长子，曾任生产队长，育有三子。',
    phone: '',
    relationType: 'birth',
  },
  {
    id: 'p_changhai_w',
    name: '王秀英',
    gender: 'female',
    birthDate: '1950-09-03',
    deceased: false,
    fatherId: null,
    spouseId: 'p_changhai',
    isMarriedIn: true,
    photo: '',
    bio: '高长海之妻。',
    phone: '138****2020',
    relationType: 'birth',
  },
  {
    id: 'p_changjiang',
    name: '高长江',
    gender: 'male',
    birthDate: '1952-05-28',
    deceased: false,
    fatherId: 'p_taiye',
    spouseId: 'p_changjiang_w',
    photo: '',
    bio: '高守业次子，退休教师，热心族谱修订。',
    phone: '139****1952',
    relationType: 'birth',
  },
  {
    id: 'p_changjiang_w',
    name: '李桂芳',
    gender: 'female',
    birthDate: '1955-02-11',
    deceased: false,
    fatherId: null,
    spouseId: 'p_changjiang',
    isMarriedIn: true,
    photo: '',
    bio: '高长江之妻。',
    phone: '',
    relationType: 'birth',
  },

  // ===== 第 2 代：父辈 =====
  {
    id: 'p_jianbo',
    name: '高建波',
    gender: 'male',
    birthDate: '1969-04-06',
    deceased: false,
    fatherId: 'p_changhai',
    spouseId: null,
    photo: '',
    bio: '高长海长子，在县城经商。',
    phone: '',
    relationType: 'birth',
  },
  {
    id: 'p_jianguo',
    name: '高建国',
    gender: 'male',
    birthDate: '1972-10-19',
    deceased: false,
    fatherId: 'p_changhai',
    spouseId: 'p_jianguo_w',
    photo: '',
    bio: '高长海次子，当前登录用户高伟之父。',
    phone: '137****1972',
    relationType: 'birth',
  },
  {
    id: 'p_jianguo_w',
    name: '张丽娟',
    gender: 'female',
    birthDate: '1974-06-22',
    deceased: false,
    fatherId: null,
    spouseId: 'p_jianguo',
    isMarriedIn: true,
    photo: '',
    bio: '高建国之妻，高伟之母。',
    phone: '',
    relationType: 'birth',
  },
  {
    id: 'p_jianjun',
    name: '高建军',
    gender: 'male',
    birthDate: '1975-12-01',
    deceased: false,
    fatherId: 'p_changhai',
    spouseId: null,
    photo: '',
    bio: '高长海三子，在外地工作。',
    phone: '',
    relationType: 'birth',
  },
  {
    id: 'p_jianhua',
    name: '高建华',
    gender: 'male',
    birthDate: '1974-08-30',
    deceased: false,
    fatherId: 'p_changjiang',
    spouseId: null,
    photo: '',
    bio: '高长江长子。',
    phone: '',
    relationType: 'birth',
  },
  {
    id: 'p_jianmei',
    name: '高建梅',
    gender: 'female',
    birthDate: '1978-03-17',
    deceased: false,
    fatherId: 'p_changjiang',
    spouseId: null,
    photo: '',
    bio: '高长江之女。',
    phone: '',
    relationType: 'birth',
  },

  // ===== 第 3 代：本人及平辈 =====
  {
    id: 'p_gaowei',
    name: '高伟',
    gender: 'male',
    birthDate: '1998-09-25',
    deceased: false,
    fatherId: 'p_jianguo',
    spouseId: null,
    photo: '',
    bio: '当前登录认证用户。软件工程师，族谱系统发起人。',
    phone: '150****1998',
    relationType: 'birth',
  },
  {
    id: 'p_gaoqiang',
    name: '高强',
    gender: 'male',
    birthDate: '2001-11-08',
    deceased: false,
    fatherId: 'p_jianguo',
    spouseId: null,
    photo: '',
    bio: '高建国次子，高伟之弟。',
    phone: '',
    relationType: 'birth',
  },
  {
    id: 'p_gaoli',
    name: '高丽',
    gender: 'female',
    birthDate: '2003-04-14',
    deceased: false,
    fatherId: 'p_jianguo',
    spouseId: null,
    photo: '',
    bio: '高建国之女，高伟之妹。',
    phone: '',
    relationType: 'birth',
  },
  {
    id: 'p_gaoyong',
    name: '高勇',
    gender: 'male',
    birthDate: '2000-07-30',
    deceased: false,
    fatherId: 'p_jianjun',
    spouseId: null,
    photo: '',
    bio: '高建军之子。',
    phone: '',
    relationType: 'birth',
  },
  {
    id: 'p_gaoming',
    name: '高明',
    gender: 'male',
    birthDate: '1997-02-03',
    deceased: false,
    fatherId: 'p_jianhua',
    spouseId: null,
    photo: '',
    bio: '高建华之子。',
    phone: '',
    relationType: 'birth',
  },
];

// 头像配色（按姓氏/性别生成稳定颜色）
export function getAvatarColor(person) {
  if (person.deceased) return '#9e9e9e';
  return person.gender === 'female' ? '#eb6f92' : '#4c7bd9';
}
